#!/bin/bash

# Make sure, what latest stable release was downloaded and you are in destination folder
  
    echo untar Redis
  
  tar xzf redis-3.2.5.tar.gz
  cd redis-3.2.5
  make
  echo 'vm.overcommit_memory = 1' >> /etc/sysctl.conf
  echo 'sysctl -w net.core.somaxconn=65535' >> /etc/rc.local
  echo 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' >> /etc/rc.local
  
  reboot
 
